twilio.json
=> added twilio.json

functions/setup.js, package.json, scripts/makeAssetsPrivate.sh, ui-src/package.json
=> FLEXY-4320 added script and setup js

functions/setup.js
=> FLEXY_4320 change in setup js

functions/__mocks__/axios.js
=> FLEXY-4320-m deleted unused mocks

CHANGELOG.md, DETAILS.md, README.md
=> FLEXY-4320 added changelog and details

ui-src/src/service/ApiService.ts
=> ApiService updates

ui-src/src/service/ChatTransferService.ts, ui-src/src/service/ProgrammableChatService.ts, ui-src/src/service/TaskRouterService.ts
=> updated services to remove protocol

package.json, ui-src/package.json
=> modified package version and removed unused package

functions/twilio-wrappers/taskrouter.private.js
=> realm update for taskrouter call

functions/chat-transfer/common/chat-operations.private.js, functions/twilio-wrappers/taskrouter.private.js
=> fixed task router call issue for stage

ui-src/src/components/TransferButton/TransferButton.tsx, ui-src/src/components/TransferButton/__tests__/__snapshots__/TransferButton.test.tsx.snap
=> FLEXY-4320 modified style of transfer button

CHANGELOG.md, package.json, twilio.json, ui-src/package.json, ui-src/src/utils/ErrorManager.ts
=> FLEXY-4320 renamed chat transfer cold to chat transfer

DETAILS.md
=> details.md updates

package.json, ui-src/package.json, ui-src/src/utils/ErrorManager.ts
=> Flexy 4441 added kibana logging

ui-src/src/service/ProgrammableChatService.ts, ui-src/src/service/TaskRouterService.ts
JIRA: [FLEXY-4614](https://issues.corp.twilio.com/browse/FLEXY-4614)
=> FLEXY-4614 deps cleanup

DETAILS.md
=> Update Details.md for adding disclaimer to not use conversations API

.github/workflows/tag.yaml, DETAILS.md
JIRA: [FLEXY-4692](https://issues.corp.twilio.com/browse/FLEXY-4692)
=> Flexy 4692 : Updated tag.yaml 

DETAILS.md
Adding Taskrouter workflow section
=> Updated DETAILS.md with Taskrouter workflow section

README.md
=> FLEXY-4692: Updated Readme

DETAILS.md
JIRA: [FLEXY-4799](https://issues.corp.twilio.com/browse/FLEXY-4799)
=> FLEXY 4799 details md updates
